feat: add allow not run workflow option
nrwl/nx-orb pull request #55
Opened 2024-01-21 21:31 UTC by eladhaim

**SEMVER Update Type:**
- [ ] Major
- [ ] Minor
- [ ] Patch

## Description:

## Motivation:

 **Closes Issues:**
-  ISSUE URL

## Checklist:

- [ ] All new jobs, commands, executors, parameters have descriptions.
- [ ] Usage Example version numbers have been updated.
- [ ] Changelog has been updated.

2024-01-24 14:33 UTC, eladhaim commented
@meeroslav can you take a look of this?

2024-02-21 18:00 UTC, uribrod approved these changes

2024-02-21 18:08 UTC, uribrod commented
Would really nice to have it!! Great contribution!

2024-06-11 12:14 UTC, mandarini commented
Hello @eladhaim ! Thank you for your contribution! I will make sure to take a look next week and see if it makes sense for us to merge this! Thank you for your patience and understanding!

2024-09-04 07:43 UTC, meeroslav commented
Hi @uribrod, the purpose of this orb is to guarantee to failure goes under the radar by ensuring to always run nx affected against the last successful run.

Both **on-hold** and **not-run** are not guaranteed to be successful so that would work against the fundamental requirement of this orb.

I don't think the feature proposal makes sense.

2024-09-04 08:24 UTC, eladhaim commented
so i will explain our needs, we are pushing some packages from our monorepo and updating our github repository in this process, adding tags and commits. Those commits has [skip ci] in the title to avoid cci to fire a build, but it' still get created in cci as a workflow with not_run status which get included in the calculation of the last workflow success .

2025-02-25 15:27 UTC, meeroslav requested changes
Few minor changes needed, otherwise looks good.

2025-02-25 15:27 UTC, meeroslav commented on src/scripts/set-shas.sh
> +RESPONSE=$(node index.js $CIRCLE_BUILD_URL $TARGET_BRANCH $PARAM_MAIN_BRANCH $PARAM_ERROR_ON_NO_SUCCESSFUL_WORKFLOW $PARAM_ALLOW_ON_HOLD $PARAM_SKIP_BRANCH_FILTER $PARAM_WORKFLOW_NAME $PARMA_ALLOW_NO
```suggestion
RESPONSE=$(node index.js $CIRCLE_BUILD_URL $TARGET_BRANCH $PARAM_MAIN_BRANCH $PARAM_ERROR_ON_NO_SUCCESSFUL_WORKFLOW $PARAM_ALLOW_ON_HOLD $PARAM_SKIP_BRANCH_FILTER $PARAM_WORKFLOW_NAME $PARAM_ALLOW_NOT_RUN)
```

This parameter cannot be last as workflow name is optional. It should follow PARAM_ALLOW_ON_HOLD

2025-02-27 10:42 UTC, meeroslav approved these changes
I made to changes to expedite the process

2025-02-27 10:42 UTC, merged